import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * /api/slate — serves the pre-built slate_data.json.
 *
 * The JSON is generated by scripts/build_slate_data.py, which is called by:
 *   python3 chef.py morning   (after each day's picks are generated)
 *   python3 chef.py deploy    (before every Vercel push)
 *
 * Keeping this route free of any "../output/picks/" references is critical:
 * Next.js file tracing follows readFileSync/existsSync calls and would bundle
 * the entire output/ directory (260MB+) into the serverless function otherwise.
 */

const SLATE_PATH = join(process.cwd(), "src", "data", "slate_data.json");

export interface SlateRow {
  id: string;
  sport: string;
  market: string;
  matchup: string;
  away_team: string;
  home_team: string;
  direction: string;
  line: number | null;
  model_prob: number | null;
  implied_prob: number | null;
  edge_pct: number;
  odds: number | null;
  odds_fmt: string;
  book: string;
  commence_time: string | null;
  away_sp: string | null;
  home_sp: string | null;
  why: string | null;
  is_card_pick: boolean;
}

interface SlateData {
  generated_at: string;
  dates: Record<string, string>;
  total: number;
  positive_ev: number;
  avg_edge: number;
  top_edge: number;
  card_picks: number;
  rows: SlateRow[];
}

function readSlate(): SlateData | null {
  if (!existsSync(SLATE_PATH)) return null;
  try {
    return JSON.parse(readFileSync(SLATE_PATH, "utf-8")) as SlateData;
  } catch {
    return null;
  }
}

export async function GET(request: Request) {
  const data = readSlate();

  if (!data) {
    return NextResponse.json(
      { error: "Slate not built yet. Run: python3 scripts/build_slate_data.py" },
      { status: 503 }
    );
  }

  const { searchParams } = new URL(request.url);
  const sportFilter = searchParams.get("sport")?.toLowerCase() ?? "all";
  const marketFilter = searchParams.get("market")?.toLowerCase() ?? "all";
  const minEdge = parseFloat(searchParams.get("min_edge") ?? "0");

  let rows = data.rows.filter((r) => r.edge_pct >= minEdge);
  if (sportFilter !== "all") rows = rows.filter((r) => r.sport === sportFilter);
  if (marketFilter !== "all") rows = rows.filter((r) => r.market === marketFilter);

  const positive = rows.filter((r) => r.edge_pct > 0).length;
  const cardPicks = rows.filter((r) => r.is_card_pick).length;
  const avgEdge = rows.length
    ? rows.reduce((s, r) => s + r.edge_pct, 0) / rows.length
    : 0;

  return NextResponse.json(
    {
      generated_at: data.generated_at,
      dates: data.dates,
      total: rows.length,
      positive_ev: positive,
      avg_edge: Math.round(avgEdge * 10) / 10,
      top_edge: rows[0]?.edge_pct ?? 0,
      card_picks: cardPicks,
      rows,
    },
    { headers: { "Cache-Control": "public, s-maxage=120, stale-while-revalidate=300" } }
  );
}
