// World Cup 2026 data types + helpers. Source: /data/wc/*.json (generated by
// `python3 chef.py wc`).

export interface WCProbs { home_win: number; draw: number; away_win: number; }

export interface WCScorer {
  player: string; share: number; exp_goals: number;
  anytime_prob: number; career_goals: number; pen_rate: number;
}

export interface WCFixture {
  id: string;
  date: string;
  time: string;
  group: string;
  round: string;
  home: string;
  away: string;
  model: WCProbs & {
    btts: number; over_2_5: number;
    exp_home: number; exp_away: number; exp_total: number;
  };
  top_scores: { score: string; prob: number }[];
  context: {
    city: string;
    host_country: string | null;
    host_side: "home" | "away" | null;
    altitude: { meters: number; favored: string | null } | null;
    net_home_adv_elo: number;
    notes: string[];
  };
  elo: { home: number; away: number };
  scorers: { home: WCScorer[]; away: WCScorer[] };
  market?: WCProbs & { prices: { home: number; away: number; draw: number } };
  blend?: WCProbs;
  edge?: { side: "home" | "draw" | "away"; pp: number };
  market_total?: {
    line: number; over: number; under: number;
    prices: { over: number; under: number }; model_over: number;
  };
}

export interface WCFuturesRow {
  team: string;
  model: number;
  market: number | null;
  blend: number;
  advance: number;
  reach_final: number;
  edge_pp: number | null;
}

export interface WCFutures {
  teams: WCFuturesRow[];
  disagreements: { model_higher: WCFuturesRow[]; model_lower: WCFuturesRow[] };
  generated: string;
  n_sims: number;
  blend_model_weight: number;
  model_fitted_on: string | null;
  kickoff: string;
}

export interface WCGroupRow {
  team: string; advance: number; champion: number; elo: number;
}
export type WCGroups = Record<string, WCGroupRow[]>;

export interface WCGoldenBootPlayer {
  player: string; team: string; exp_goals: number; share: number;
}
export interface WCGoldenBoot {
  players: WCGoldenBootPlayer[];
  generated: string; n_sims: number; kickoff: string;
}

export interface WCMeta {
  generated: string; n_sims: number; blend_model_weight: number;
  model_fitted_on: string | null; n_fixtures: number; n_priced: number;
  kickoff: string;
}

export interface WCCalibBin { pred: number; actual: number; n: number; }
export interface WCAccuracy {
  generated: string;
  n_tournaments: number;
  n_matches: number;
  min_year: number;
  aggregate: {
    brier_1x2: number; brier_naive: number;
    log_loss: number; log_loss_naive: number;
    modal_acc: number;
    brier_ou: number; brier_ou_naive: number; over_rate: number;
  };
  calibration_favorite: WCCalibBin[];
  calibration_over25: WCCalibBin[];
  per_tournament: { label: string; n: number; brier_1x2: number; log_loss: number; acc: number }[];
}

// ── fetch ──
export async function getJSON<T>(path: string): Promise<T | null> {
  try {
    const r = await fetch(path, { cache: "no-store" });
    if (!r.ok) return null;
    return (await r.json()) as T;
  } catch { return null; }
}

// ── format ──
export const pct = (v: number, d = 0) => `${(v * 100).toFixed(d)}%`;
export const odds = (o: number | undefined | null) =>
  o == null ? "—" : o > 0 ? `+${o}` : `${o}`;

// 3-letter codes for compact display; falls back to first 3 letters upper.
const CODE: Record<string, string> = {
  "United States": "USA", "South Korea": "KOR", "South Africa": "RSA",
  "Saudi Arabia": "KSA", "Czech Republic": "CZE", "Ivory Coast": "CIV",
  "DR Congo": "COD", "New Zealand": "NZL", "Costa Rica": "CRC",
  "Cape Verde": "CPV", "Bosnia and Herzegovina": "BIH",
};
export function code(team: string): string {
  if (CODE[team]) return CODE[team];
  const w = team.split(" ");
  return (w.length > 1 ? w.map(x => x[0]).join("") : team.slice(0, 3)).toUpperCase().slice(0, 3);
}

// ── flags: team (martj42 canonical) → ISO 3166-1 alpha-2 (flagcdn code) ──
// England/Scotland use GB subdivision codes that flagcdn serves.
export const FLAG_ISO: Record<string, string> = {
  "Algeria": "dz", "Argentina": "ar", "Australia": "au", "Austria": "at",
  "Belgium": "be", "Bosnia and Herzegovina": "ba", "Brazil": "br", "Canada": "ca",
  "Cape Verde": "cv", "Colombia": "co", "Croatia": "hr", "Curaçao": "cw",
  "Czech Republic": "cz", "DR Congo": "cd", "Ecuador": "ec", "Egypt": "eg",
  "England": "gb-eng", "France": "fr", "Germany": "de", "Ghana": "gh",
  "Haiti": "ht", "Iran": "ir", "Iraq": "iq", "Ivory Coast": "ci",
  "Japan": "jp", "Jordan": "jo", "Mexico": "mx", "Morocco": "ma",
  "Netherlands": "nl", "New Zealand": "nz", "Norway": "no", "Panama": "pa",
  "Paraguay": "py", "Portugal": "pt", "Qatar": "qa", "Saudi Arabia": "sa",
  "Scotland": "gb-sct", "Senegal": "sn", "South Africa": "za", "South Korea": "kr",
  "Spain": "es", "Sweden": "se", "Switzerland": "ch", "Tunisia": "tn",
  "Turkey": "tr", "United States": "us", "Uruguay": "uy", "Uzbekistan": "uz",
  // common non-2026 nations that show up in futures markets / older data
  "Italy": "it", "Wales": "gb-wls", "Nigeria": "ng", "Costa Rica": "cr",
  "Denmark": "dk", "Poland": "pl", "Serbia": "rs", "Peru": "pe", "Chile": "cl",
};

export function flagUrl(team: string): string | null {
  const iso = FLAG_ISO[team];
  return iso ? `https://flagcdn.com/${iso}.svg` : null;
}

// kickoff time "13:00 UTC-6" → just "13:00" label
export const clock = (t: string) => (t || "").split(" ")[0] || "";

// Live Elo ladder: every nation's current rating, pulled straight from the
// fixtures the site is already showing. Dedupes (a team appears in 3 group
// games) and sorts strongest first — proof the rating is real, not decorative.
export function eloLadder(fixtures: WCFixture[]): { team: string; elo: number }[] {
  const m = new Map<string, number>();
  for (const f of fixtures) {
    if (f.elo?.home != null) m.set(f.home, Math.round(f.elo.home));
    if (f.elo?.away != null) m.set(f.away, Math.round(f.elo.away));
  }
  return [...m.entries()].map(([team, elo]) => ({ team, elo })).sort((a, b) => b.elo - a.elo);
}

// Elo intuition: expected match score from a rating gap (standard Elo curve).
// We surface this so "a 100-point edge" means something concrete to a reader.
export function eloExpected(diff: number): number {
  return 1 / (1 + Math.pow(10, -diff / 400));
}

// "2026-06-07T21:26:12Z" → "3 hours ago" / "just now". For freshness badges.
export function timeAgo(iso: string | null | undefined): string {
  if (!iso) return "";
  const t = new Date(iso).getTime();
  if (Number.isNaN(t)) return "";
  const s = Math.max(0, Math.floor((Date.now() - t) / 1000));
  if (s < 90) return "just now";
  const m = Math.floor(s / 60);
  if (m < 60) return `${m} min ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h} hour${h === 1 ? "" : "s"} ago`;
  const d = Math.floor(h / 24);
  return `${d} day${d === 1 ? "" : "s"} ago`;
}

export const KICKOFF = new Date("2026-06-11T18:00:00Z");
export function daysToKickoff(): number {
  return Math.max(0, Math.ceil((KICKOFF.getTime() - Date.now()) / 86400000));
}
