"""
Auto-generate Instagram captions for pick cards and props cards.

Usage:
    from src.output.captions import picks_caption, props_caption
    print(picks_caption(picks_list, date_str="Apr 14"))
    print(props_caption(props_list, date_str="Apr 14"))
"""
from __future__ import annotations

import math
import random
from datetime import date


# ─────────────────────────────────────────────────────────────────────────────
# Hashtag sets — rotate to avoid shadowban (IG penalizes using same tags daily)
# ─────────────────────────────────────────────────────────────────────────────

_CORE_TAGS = [
    "#sportsbetting", "#mlbpicks", "#baseballbetting", "#bettingtips",
    "#freepicks", "#mlb", "#baseball", "#sportspicks",
]

_ROTATION_A = [
    "#bettingcommunity", "#sharpbetting", "#valuebet", "#edgebetting",
    "#mlbodds", "#moneyline", "#handicapper", "#sportsbettingpicks",
]

_ROTATION_B = [
    "#positiveev", "#kellycriterion", "#bettingmodel", "#AIbetting",
    "#datadrivenbetting", "#mlbpredictions", "#algorithmbets", "#quantbetting",
]

_ROTATION_C = [
    "#baseballpicks", "#mlbtoday", "#baseballfan", "#baseballlife",
    "#mlbgames", "#baseballseason", "#todaysgames", "#sportstalk",
]

_ROTATION_SETS = [_ROTATION_A, _ROTATION_B, _ROTATION_C]


def _hashtags(d: date | None = None) -> str:
    """Pick a rotation set based on day of week to avoid repetition."""
    d = d or date.today()
    rotation = _ROTATION_SETS[d.weekday() % 3]
    tags = _CORE_TAGS[:5] + rotation[:5]
    return " ".join(tags)


# ─────────────────────────────────────────────────────────────────────────────
# Opening hook variants — rotate for fresh content
# ─────────────────────────────────────────────────────────────────────────────

_PICKS_HOOKS = [
    "The model ran all night. Here's what it found 👇",
    "AI ran the numbers on today's slate. These 5 games have edge.",
    "Dropping today's picks. Model found +EV on these lines 🔒",
    "Sharp money targets for today. Model-verified, book-beatable.",
    "Today's slate is live. Model flagged these 5 as best value.",
    "The algorithm doesn't guess. It found edge on these today 📊",
    "Free picks for today's MLB slate. Backed by data, not feelings.",
    "Model just finished processing today's lines. Here's the output:",
]

_PROPS_HOOKS = [
    "Props sheet is up. These pitcher & batter lines have real edge 🎯",
    "Found some fat lines in today's player props. Model says bet these.",
    "Sportsbooks mispriced these props today. We found them first.",
    "Today's player props with model edge — pitcher Ks, hits, and more.",
    "Props slate for today. AI projected vs book line, pick the overs.",
    "The props market moves slower than moneylines. That's where edge hides.",
]


def picks_caption(
    picks: list[dict],
    date_str: str | None = None,
    record: str | None = None,
    card_date: date | None = None,
) -> str:
    """
    Generate Instagram caption for the main picks card.

    Args:
        picks: list of pick dicts (same format as picks_card.json)
        date_str: e.g. "Apr 14" — auto-formatted from card_date if not given
        record: optional record string e.g. "12-8 L20"
        card_date: date object for hashtag rotation
    """
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")

    hook = _PICKS_HOOKS[d.toordinal() % len(_PICKS_HOOKS)]

    # Build pick lines
    pick_lines = []
    for i, p in enumerate(picks[:5]):
        team = p.get("Team", "")
        odds = int(p.get("BestOdds", 0) or 0)
        edge = float(p.get("Edge", 0) or 0)
        mkt = str(p.get("Market", "moneyline")).lower()
        book = p.get("Sportsbook", "")
        odds_str = f"{odds:+d}" if odds else ""
        # Totals/spreads store edge in runs, not probability — display differently
        if mkt in ("total", "spread"):
            edge_str = f"+{edge:.1f} run edge"
        else:
            edge_str = f"+{edge*100:.0f}% edge"
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        book_str = f" [{book}]" if book else ""
        matchup = p.get("Matchup", "")
        matchup_str = f" ({matchup})" if matchup and mkt in ("total", "spread") else ""
        pick_lines.append(f"{prefix} {team}{matchup_str} {odds_str} — {edge_str}{book_str}")

    picks_block = "\n".join(pick_lines)

    record_line = f"\n📈 Model record: {record}" if record else ""

    caption = f"""{hook}

{date_str} MLB Picks 🔥
━━━━━━━━━━━━━━━
{picks_block}
━━━━━━━━━━━━━━━{record_line}

All picks generated by our ensemble model (XGBoost + Pythagorean). We track every result publicly — link in bio.

Not financial advice. Bet responsibly. 21+

{_hashtags(d)}"""

    return caption.strip()


def props_caption(
    props: list[dict],
    date_str: str | None = None,
    card_date: date | None = None,
) -> str:
    """
    Generate Instagram caption for the player props card.
    """
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")

    hook = _PROPS_HOOKS[d.toordinal() % len(_PROPS_HOOKS)]

    # Build prop lines — group by market type
    k_props  = [p for p in props if "strikeout" in p.get("market", "")]
    hit_props = [p for p in props if "hit" in p.get("market", "") and "strikeout" not in p.get("market", "")]
    hr_props = [p for p in props if "home_run" in p.get("market", "")]

    lines = []
    if k_props:
        lines.append("⚡ Strikeouts:")
        for p in k_props[:3]:
            proj = p.get("projected", "")
            proj_str = f" (proj {proj})" if proj else ""
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} Ks{proj_str} {p.get('odds', ''):+d} [{p.get('book','')}]")

    if hit_props:
        lines.append("🎯 Hits:")
        for p in hit_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']}{' Hits' if 'hit' in p.get('market','') else ''} {p.get('odds', ''):+d} [{p.get('book','')}]")

    if hr_props:
        lines.append("💣 Home Runs:")
        for p in hr_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} HR {p.get('odds', ''):+d} [{p.get('book','')}]")

    props_block = "\n".join(lines) if lines else "\n".join(
        f"• {p['player']} {p['direction']} {p['line']} — {p.get('edge_pct',0)}% edge [{p.get('book','')}]"
        for p in props[:6]
    )

    # Hashtags with props-specific tags mixed in
    base_tags = _hashtags(d)
    extra = "#playerpropbets #propbets #mlbprops #strikeoutprop #nhlpicks"

    caption = f"""{hook}

{date_str} Player Props 🧮
━━━━━━━━━━━━━━━
{props_block}
━━━━━━━━━━━━━━━

Model projects expected Ks using pitcher K/9 rate, last 10 starts, and opposing lineup OPS. We only post when we find real edge vs the book line.

Full slate in the props card above. Swipe for game picks 👆

Not financial advice. Bet responsibly. 21+

{base_tags} {extra}"""

    return caption.strip()


_NRFI_HOOKS = [
    "First inning is where the edge is. Model found these NRFI/YRFI plays 🔒",
    "Books misprice first innings more than any other market. Here's what we found.",
    "NRFI bets hit at 42% historically. Model says these games are above that. 📊",
    "First pitch edge. Model projects first-inning run probability for every game.",
    "The sharp play on first innings — NRFI or YRFI, model picks the edge side.",
    "Starting pitcher K/9 and ERA point to these first-inning plays today.",
]


def nrfi_caption(
    games: list[dict],
    date_str: str | None = None,
    card_date: date | None = None,
) -> str:
    """Generate Instagram caption for the NRFI/YRFI card."""
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")
    hook = _NRFI_HOOKS[d.toordinal() % len(_NRFI_HOOKS)]

    lines = []
    for i, g in enumerate(games[:5]):
        direction = g.get("direction", "NRFI")
        away = g.get("away_team", "")
        home = g.get("home_team", "")
        odds = g.get("odds")
        edge_pct = g.get("edge_pct")
        proj = g.get("projected_nrfi", 0.0)
        book = g.get("book", "")
        odds_str = f"{int(odds):+d}" if odds is not None else ""
        edge_str = f"+{edge_pct:.1f}% edge" if edge_pct else f"proj {proj*100:.0f}% NRFI"
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        book_str = f" [{book}]" if book else ""
        lines.append(f"{prefix} {away} @ {home} — {direction} {odds_str} {edge_str}{book_str}")

    block = "\n".join(lines)
    tags = _hashtags(d)

    caption = f"""{hook}

{date_str} NRFI / YRFI Plays 🎯
━━━━━━━━━━━━━━━
{block}
━━━━━━━━━━━━━━━

Model uses pitcher ERA, K/9 rate, and last 10 starts to project first-inning run probability for both teams. NRFI = neither team scores in the 1st.

Not financial advice. Bet responsibly. 21+

{tags} #nrfi #yrfi #firstinning #nrfibets #mlbprops"""

    return caption.strip()


def print_both_captions(
    picks: list[dict],
    props: list[dict],
    card_date: date | None = None,
    record: str | None = None,
) -> None:
    """Print both captions to terminal, ready to copy-paste."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")

    print("\n" + "="*60)
    print("CAPTION 1 — PICKS CARD")
    print("="*60)
    print(picks_caption(picks, date_str=date_str, record=record, card_date=d))

    print("\n" + "="*60)
    print("CAPTION 2 — PROPS CARD")
    print("="*60)
    print(props_caption(props, date_str=date_str, card_date=d))
    print("="*60 + "\n")
