"""
Auto-generate Instagram captions for pick cards and props cards.

Usage:
    from src.output.captions import picks_caption, props_caption
    print(picks_caption(picks_list, date_str="Apr 14"))
    print(props_caption(props_list, date_str="Apr 14"))
"""
from __future__ import annotations

import math
import random
from datetime import date


# ─────────────────────────────────────────────────────────────────────────────
# Hashtag sets — rotate to avoid shadowban (IG penalizes using same tags daily)
# ─────────────────────────────────────────────────────────────────────────────

_CORE_TAGS = [
    "#sportsbetting", "#mlbpicks", "#baseballbetting", "#bettingtips",
    "#freepicks", "#mlb", "#baseball", "#sportspicks",
]

_ROTATION_A = [
    "#bettingcommunity", "#sharpbetting", "#valuebet", "#edgebetting",
    "#mlbodds", "#moneyline", "#handicapper", "#sportsbettingpicks",
]

_ROTATION_B = [
    "#positiveev", "#kellycriterion", "#bettingmodel", "#AIbetting",
    "#datadrivenbetting", "#mlbpredictions", "#algorithmbets", "#quantbetting",
]

_ROTATION_C = [
    "#baseballpicks", "#mlbtoday", "#baseballfan", "#baseballlife",
    "#mlbgames", "#baseballseason", "#todaysgames", "#sportstalk",
]

_ROTATION_SETS = [_ROTATION_A, _ROTATION_B, _ROTATION_C]


def _hashtags(d: date | None = None) -> str:
    """Pick a rotation set based on day of week to avoid repetition."""
    d = d or date.today()
    rotation = _ROTATION_SETS[d.weekday() % 3]
    tags = _CORE_TAGS[:5] + rotation[:5]
    return " ".join(tags)


# ─────────────────────────────────────────────────────────────────────────────
# Opening hook variants — rotate for fresh content
# ─────────────────────────────────────────────────────────────────────────────

_PICKS_HOOKS = [
    "The model ran all night. Here's what it found 👇",
    "AI ran the numbers on today's slate. These 5 games have edge.",
    "Dropping today's picks. Model found +EV on these lines 🔒",
    "Sharp money targets for today. Model-verified, book-beatable.",
    "Today's slate is live. Model flagged these 5 as best value.",
    "The algorithm doesn't guess. It found edge on these today 📊",
    "Free picks for today's MLB slate. Backed by data, not feelings.",
    "Model just finished processing today's lines. Here's the output:",
]

_PROPS_HOOKS = [
    "Props sheet is up. These pitcher & batter lines have real edge 🎯",
    "Found some fat lines in today's player props. Model says bet these.",
    "Sportsbooks mispriced these props today. We found them first.",
    "Today's player props with model edge — pitcher Ks, hits, and more.",
    "Props slate for today. AI projected vs book line, pick the overs.",
    "The props market moves slower than moneylines. That's where edge hides.",
]


def picks_caption(
    picks: list[dict],
    date_str: str | None = None,
    record: str | None = None,
    card_date: date | None = None,
) -> str:
    """
    Generate Instagram caption for the main picks card.

    Args:
        picks: list of pick dicts (same format as picks_card.json)
        date_str: e.g. "Apr 14" — auto-formatted from card_date if not given
        record: optional record string e.g. "12-8 L20"
        card_date: date object for hashtag rotation
    """
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")

    hook = _PICKS_HOOKS[d.toordinal() % len(_PICKS_HOOKS)]

    # Build pick lines
    pick_lines = []
    for i, p in enumerate(picks[:5]):
        team = p.get("Team", "")
        odds = int(p.get("BestOdds", 0) or 0)
        edge = float(p.get("Edge", 0) or 0)
        mkt = str(p.get("Market", "moneyline")).lower()
        book = p.get("Sportsbook", "")
        odds_str = f"{odds:+d}" if odds else ""
        # Totals/spreads store edge in runs, not probability — display differently
        if mkt in ("total", "spread"):
            edge_str = f"+{edge:.1f} run edge"
        else:
            edge_str = f"+{edge*100:.0f}% edge"
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        book_str = f" [{book}]" if book else ""
        matchup = p.get("Matchup", "")
        matchup_str = f" ({matchup})" if matchup and mkt in ("total", "spread") else ""
        pick_lines.append(f"{prefix} {team}{matchup_str} {odds_str} — {edge_str}{book_str}")

    picks_block = "\n".join(pick_lines)

    record_line = f"\n📈 Model record: {record}" if record else ""

    caption = f"""{hook}

{date_str} MLB Picks 🔥
━━━━━━━━━━━━━━━
{picks_block}
━━━━━━━━━━━━━━━{record_line}

All picks generated by our ensemble model (XGBoost + Pythagorean). We track every result publicly — link in bio.

Not financial advice. Bet responsibly. 21+

{_hashtags(d)}"""

    return caption.strip()


def props_caption(
    props: list[dict],
    date_str: str | None = None,
    card_date: date | None = None,
) -> str:
    """
    Generate Instagram caption for the player props card.
    """
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")

    hook = _PROPS_HOOKS[d.toordinal() % len(_PROPS_HOOKS)]

    # Build prop lines — group by market type
    k_props  = [p for p in props if "strikeout" in p.get("market", "")]
    hit_props = [p for p in props if "hit" in p.get("market", "") and "strikeout" not in p.get("market", "")]
    hr_props = [p for p in props if "home_run" in p.get("market", "")]

    lines = []
    if k_props:
        lines.append("⚡ Strikeouts:")
        for p in k_props[:3]:
            proj = p.get("projected", "")
            proj_str = f" (proj {proj})" if proj else ""
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} Ks{proj_str} {p.get('odds', ''):+d} [{p.get('book','')}]")

    if hit_props:
        lines.append("🎯 Hits:")
        for p in hit_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']}{' Hits' if 'hit' in p.get('market','') else ''} {p.get('odds', ''):+d} [{p.get('book','')}]")

    if hr_props:
        lines.append("💣 Home Runs:")
        for p in hr_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} HR {p.get('odds', ''):+d} [{p.get('book','')}]")

    props_block = "\n".join(lines) if lines else "\n".join(
        f"• {p['player']} {p['direction']} {p['line']} — {p.get('edge_pct',0)}% edge [{p.get('book','')}]"
        for p in props[:6]
    )

    # Hashtags with props-specific tags mixed in
    base_tags = _hashtags(d)
    extra = "#playerpropbets #propbets #mlbprops #strikeoutprop #nhlpicks"

    caption = f"""{hook}

{date_str} Player Props 🧮
━━━━━━━━━━━━━━━
{props_block}
━━━━━━━━━━━━━━━

Model projects expected Ks using pitcher K/9 rate, last 10 starts, and opposing lineup OPS. We only post when we find real edge vs the book line.

Full slate in the props card above. Swipe for game picks 👆

Not financial advice. Bet responsibly. 21+

{base_tags} {extra}"""

    return caption.strip()


_NRFI_HOOKS = [
    "First inning is where the edge is. Model found these NRFI/YRFI plays 🔒",
    "Books misprice first innings more than any other market. Here's what we found.",
    "NRFI bets hit at 42% historically. Model says these games are above that. 📊",
    "First pitch edge. Model projects first-inning run probability for every game.",
    "The sharp play on first innings — NRFI or YRFI, model picks the edge side.",
    "Starting pitcher K/9 and ERA point to these first-inning plays today.",
]


def nrfi_caption(
    games: list[dict],
    date_str: str | None = None,
    card_date: date | None = None,
) -> str:
    """Generate Instagram caption for the NRFI/YRFI card."""
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")
    hook = _NRFI_HOOKS[d.toordinal() % len(_NRFI_HOOKS)]

    lines = []
    for i, g in enumerate(games[:5]):
        direction = g.get("direction", "NRFI")
        away = g.get("away_team", "")
        home = g.get("home_team", "")
        odds = g.get("odds")
        edge_pct = g.get("edge_pct")
        proj = g.get("projected_nrfi", 0.0)
        book = g.get("book", "")
        odds_str = f"{int(odds):+d}" if odds is not None else ""
        edge_str = f"+{edge_pct:.1f}% edge" if edge_pct else f"proj {proj*100:.0f}% NRFI"
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        book_str = f" [{book}]" if book else ""
        lines.append(f"{prefix} {away} @ {home} — {direction} {odds_str} {edge_str}{book_str}")

    block = "\n".join(lines)
    tags = _hashtags(d)

    caption = f"""{hook}

{date_str} NRFI / YRFI Plays 🎯
━━━━━━━━━━━━━━━
{block}
━━━━━━━━━━━━━━━

Model uses pitcher ERA, K/9 rate, and last 10 starts to project first-inning run probability for both teams. NRFI = neither team scores in the 1st.

Not financial advice. Bet responsibly. 21+

{tags} #nrfi #yrfi #firstinning #nrfibets #mlbprops"""

    return caption.strip()


def print_both_captions(
    picks: list[dict],
    props: list[dict],
    card_date: date | None = None,
    record: str | None = None,
) -> None:
    """Print both captions to terminal, ready to copy-paste."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")

    print("\n" + "="*60)
    print("CAPTION 1 — PICKS CARD")
    print("="*60)
    print(picks_caption(picks, date_str=date_str, record=record, card_date=d))

    print("\n" + "="*60)
    print("CAPTION 2 — PROPS CARD")
    print("="*60)
    print(props_caption(props, date_str=date_str, card_date=d))
    print("="*60 + "\n")


# ─────────────────────────────────────────────────────────────────────────────
# NBA Captions
# ─────────────────────────────────────────────────────────────────────────────

_NBA_CORE_TAGS = [
    "#NBA", "#NBAPlayoffs", "#sportsbetting", "#NBApicks", "#bettingtips",
]

_NBA_ROTATION_A = [
    "#NBATwitter", "#sharpbetting", "#valuebet", "#edgebetting",
    "#NBAodds", "#moneyline", "#handicapper", "#NBAspread",
]

_NBA_ROTATION_B = [
    "#positiveev", "#kellycriterion", "#bettingmodel", "#AIbetting",
    "#datadrivenbetting", "#NBApredictions", "#algorithmbets", "#quantbetting",
]

_NBA_ROTATION_C = [
    "#basketballpicks", "#NBAtoday", "#NBAbasketball", "#basketballbetting",
    "#NBAgames", "#playoff", "#sportspicks", "#sportstalk",
]

_NBA_ROTATION_SETS = [_NBA_ROTATION_A, _NBA_ROTATION_B, _NBA_ROTATION_C]

_PLAYIN_TAGS = "#PlayInTournament #NBAPlayIn #playin"
_PLAYOFFS_TAGS = "#NBAPlayoffs2026 #playoffs #NBAplayoff"


def _nba_hashtags(d: date | None = None, context_label: str = "NBA") -> str:
    d = d or date.today()
    rotation = _NBA_ROTATION_SETS[d.weekday() % 3]
    tags = _NBA_CORE_TAGS[:4] + rotation[:4]
    extra = ""
    if "PLAY-IN" in context_label.upper():
        extra = _PLAYIN_TAGS
    elif "PLAYOFF" in context_label.upper():
        extra = _PLAYOFFS_TAGS
    return " ".join(tags) + (" " + extra if extra else "")


_NBA_PICKS_HOOKS = [
    "Play-In Tournament is here. Model locked in these edges 🏀",
    "NBA Playoffs. Model ran all night. These lines have value.",
    "Dropped the NBA picks. AI found edge on tonight's games 📊",
    "Sharps are on these tonight. Model confirms the edge 🔒",
    "Tonight's NBA slate — algorithm found the best value plays.",
    "Post-season intensity. Pre-game edge. These are the plays.",
    "Model projected every matchup. These are the ones worth betting.",
    "NBA picks are live. Backed by efficiency ratings, not opinions 💡",
]

_NBA_PLAYIN_HOOKS = [
    "Play-In Tournament TONIGHT. Season on the line — model found the edges 🏀",
    "Win or go home. Model ran tonight's Play-In matchups. Here's what it found.",
    "Play-In picks are live. One loss ends a season — get on the right side 🔒",
    "Tonight's Play-In games. AI model projected both matchups. These are the plays.",
]

_NBA_PROPS_HOOKS = [
    "NBA props sheet is up. Player lines with real model edge 🎯",
    "Sportsbooks mispriced these player props. We found them first.",
    "Tonight's NBA player props — PTS, REB, AST lines with edge.",
    "Props market moves slower on playoff games. That's where edge hides.",
    "Found fat lines in today's NBA props. Model says bet these.",
    "Best player prop edges for tonight's NBA slate. Model-verified.",
]


def nba_picks_caption(
    picks: list[dict],
    date_str: str | None = None,
    record: str | None = None,
    card_date: date | None = None,
    context_label: str = "NBA",
) -> str:
    """Generate Instagram caption for NBA game picks card."""
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")

    is_playin = "PLAY-IN" in context_label.upper()
    hooks = _NBA_PLAYIN_HOOKS if is_playin else _NBA_PICKS_HOOKS
    hook = hooks[d.toordinal() % len(hooks)]

    label = context_label if context_label != "NBA" else "NBA"

    pick_lines = []
    seen_matchups: set = set()
    for i, p in enumerate(picks[:6]):
        matchup  = p.get("matchup", "")
        market   = p.get("market", "spread")
        team_str = p.get("team", "")
        odds     = int(p.get("best_odds", 0) or 0)
        edge_pct = float(p.get("edge_pct", 0) or 0)
        book     = p.get("sportsbook", "")
        key = (matchup, market, team_str)
        if key in seen_matchups:
            continue
        seen_matchups.add(key)
        odds_str = f"{odds:+d}" if odds else ""
        edge_str = f"+{edge_pct:.1f}% edge"
        book_str = f" [{book}]" if book else ""
        prefix   = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        if market == "total":
            pick_lines.append(f"{prefix} {team_str} ({matchup.split(' @ ')[0][:3].upper()} vs {matchup.split(' @ ')[-1][:3].upper()}) {odds_str} — {edge_str}{book_str}")
        elif market == "spread":
            pick_lines.append(f"{prefix} {team_str} {odds_str} — {edge_str}{book_str}")
        else:
            pick_lines.append(f"{prefix} {team_str} ML {odds_str} — {edge_str}{book_str}")

    picks_block = "\n".join(pick_lines)
    record_line = f"\n📈 Model record: {record}" if record else ""
    tags = _nba_hashtags(d, context_label)

    caption = f"""{hook}

{date_str} {label} Picks 🔥
━━━━━━━━━━━━━━━
{picks_block}
━━━━━━━━━━━━━━━{record_line}

Picks generated by our efficiency-rating model (ORtg/DRtg/Pace). We track every result publicly — link in bio.

Not financial advice. Bet responsibly. 21+

{tags}"""

    return caption.strip()


def nba_props_caption(
    props: list[dict],
    date_str: str | None = None,
    card_date: date | None = None,
    context_label: str = "NBA",
) -> str:
    """Generate Instagram caption for NBA player props card."""
    d = card_date or date.today()
    date_str = date_str or d.strftime("%b %-d")
    hook = _NBA_PROPS_HOOKS[d.toordinal() % len(_NBA_PROPS_HOOKS)]

    # Group by stat type
    pts_props = [p for p in props if p.get("market") == "player_points"]
    reb_props = [p for p in props if p.get("market") == "player_rebounds"]
    ast_props = [p for p in props if p.get("market") == "player_assists"]
    pra_props = [p for p in props if p.get("market") in ("player_pra", "player_points_rebounds_assists")]
    other_props = [p for p in props if p.get("market") not in (
        "player_points", "player_rebounds", "player_assists",
        "player_pra", "player_points_rebounds_assists",
    )]

    lines = []
    if pts_props:
        lines.append("🔥 Points:")
        for p in pts_props[:3]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} PTS (proj {p.get('projected', '')}) {p.get('odds', 0):+d} [{p.get('book','')}]")
    if reb_props:
        lines.append("💪 Rebounds:")
        for p in reb_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} REB {p.get('odds', 0):+d} [{p.get('book','')}]")
    if ast_props:
        lines.append("🎯 Assists:")
        for p in ast_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} AST {p.get('odds', 0):+d} [{p.get('book','')}]")
    if pra_props:
        lines.append("📊 PRA Combo:")
        for p in pra_props[:2]:
            lines.append(f"  • {p['player']} {p['direction']} {p['line']} PRA {p.get('odds', 0):+d} [{p.get('book','')}]")
    if not lines:
        for p in props[:6]:
            mkt = p.get("market", "").split("_")[-1].upper()
            lines.append(f"• {p['player']} {p['direction']} {p['line']} {mkt} — {p.get('edge_pct',0):.1f}% edge [{p.get('book','')}]")

    props_block = "\n".join(lines)
    tags = _nba_hashtags(d, context_label)
    extra_tags = "#NBApropbets #propbets #NBAprops #pointsprop #reboundsprop"

    caption = f"""{hook}

{date_str} NBA Player Props 🧮
━━━━━━━━━━━━━━━
{props_block}
━━━━━━━━━━━━━━━

Model projects each stat using season averages + opponent defensive rating. Only posts when we find real edge vs the book line.

Swipe for game picks 👆

Not financial advice. Bet responsibly. 21+

{tags} {extra_tags}"""

    return caption.strip()


def nba_spread_caption(
    picks: list[dict],
    card_date: date | None = None,
    context_label: str = "NBA",
) -> str:
    """Caption for NBA spread card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    spread_picks = [p for p in picks if p.get("market") == "spread"][:5]
    lines = []
    for i, p in enumerate(spread_picks):
        team = p.get("team", "")
        odds = int(p.get("best_odds", 0) or 0)
        edge = float(p.get("edge_pct", 0) or 0)
        book = p.get("sportsbook", "")
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        lines.append(f"{prefix} {team} {odds:+d} — +{edge:.1f}% edge [{book}]")
    tags = _nba_hashtags(d, context_label)
    return f"""Spread value on tonight's {context_label} slate. Model found real edge on these lines.

{date_str} {context_label} Spreads 📐
━━━━━━━━━━━━━━━
{chr(10).join(lines)}
━━━━━━━━━━━━━━━

Model uses ORtg/DRtg/Pace efficiency ratings. Every pick tracked publicly — link in bio.

Not financial advice. Bet responsibly. 21+

{tags} #NBAspread #spreadbetting #NBAlines""".strip()


def nba_moneyline_caption(
    picks: list[dict],
    card_date: date | None = None,
    context_label: str = "NBA",
) -> str:
    """Caption for NBA moneyline card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    ml_picks = [p for p in picks if p.get("market") in ("moneyline", "h2h")][:5]
    lines = []
    for i, p in enumerate(ml_picks):
        team = p.get("team", "")
        odds = int(p.get("best_odds", 0) or 0)
        edge = float(p.get("edge_pct", 0) or 0)
        book = p.get("sportsbook", "")
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        lines.append(f"{prefix} {team} ML {odds:+d} — +{edge:.1f}% edge [{book}]")
    tags = _nba_hashtags(d, context_label)
    return f"""Model found moneyline value tonight. These teams are underpriced.

{date_str} {context_label} Moneylines 💰
━━━━━━━━━━━━━━━
{chr(10).join(lines)}
━━━━━━━━━━━━━━━

Model uses ORtg/DRtg/Pace efficiency ratings. Every pick tracked publicly — link in bio.

Not financial advice. Bet responsibly. 21+

{tags} #NBAmoneyline #NBAml""".strip()


def nba_totals_caption(
    picks: list[dict],
    card_date: date | None = None,
    context_label: str = "NBA",
) -> str:
    """Caption for NBA totals card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    total_picks = [p for p in picks if p.get("market") == "total"][:5]
    lines = []
    for i, p in enumerate(total_picks):
        team = p.get("team", "")
        odds = int(p.get("best_odds", 0) or 0)
        edge = float(p.get("edge_pct", 0) or 0)
        book = p.get("sportsbook", "")
        matchup = p.get("matchup", "")
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        lines.append(f"{prefix} {team} ({matchup}) {odds:+d} — +{edge:.1f}% edge [{book}]")
    tags = _nba_hashtags(d, context_label)
    return f"""Model projected tonight's totals. These lines are off.

{date_str} {context_label} Totals 📊
━━━━━━━━━━━━━━━
{chr(10).join(lines)}
━━━━━━━━━━━━━━━

Pace + ORtg/DRtg model projects the final score of every game. Only posting where we find edge.

Not financial advice. Bet responsibly. 21+

{tags} #NBAtotals #NBAovers #NBAunders""".strip()


def nba_pick_of_day_caption(
    pick: dict,
    card_date: date | None = None,
    context_label: str = "NBA",
    record: str | None = None,
) -> str:
    """Caption for NBA pick of the day card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    team = pick.get("team", "")
    odds = int(pick.get("best_odds", 0) or 0)
    edge = float(pick.get("edge_pct", 0) or 0)
    book = pick.get("sportsbook", "")
    market = pick.get("market", "spread")
    matchup = pick.get("matchup", "")
    mkt_label = "ML" if market in ("moneyline", "h2h") else ("O/U" if market == "total" else "SPREAD")
    record_line = f"\n📈 Season record: {record}" if record else ""
    tags = _nba_hashtags(d, context_label)
    return f"""One pick. Highest edge on the board tonight.

🔒 {date_str} {context_label} PICK OF THE DAY
━━━━━━━━━━━━━━━
{team} [{mkt_label}] {odds:+d}
+{edge:.1f}% model edge · {book}
Game: {matchup}
━━━━━━━━━━━━━━━{record_line}

Every pick is timestamped and auto-graded. Track record in bio.

Not financial advice. Bet responsibly. 21+

{tags} #pickoftheday #NBAbestbet #bestbet""".strip()


def nba_slate_caption(
    picks: list[dict],
    card_date: date | None = None,
    context_label: str = "NBA",
    record: str | None = None,
) -> str:
    """Caption for NBA full slate card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    lines = []
    for i, p in enumerate(picks[:5]):
        team = p.get("team", "")
        odds = int(p.get("best_odds", 0) or 0)
        edge = float(p.get("edge_pct", 0) or 0)
        book = p.get("sportsbook", "")
        market = p.get("market", "spread")
        mkt_label = "ML" if market in ("moneyline", "h2h") else ("O/U" if market == "total" else "RL")
        prefix = "🔒" if i == 0 else ("📌" if i < 3 else "•")
        lines.append(f"{prefix} {team} [{mkt_label}] {odds:+d} — +{edge:.1f}% [{book}]")
    record_line = f"\n📈 Season record: {record}" if record else ""
    tags = _nba_hashtags(d, context_label)
    return f"""Full slate. Best 5 bets across every market tonight.

{date_str} {context_label} Full Slate 🗒️
━━━━━━━━━━━━━━━
{chr(10).join(lines)}
━━━━━━━━━━━━━━━{record_line}

Model ranks every bet by edge. Spread, ML, and totals all included.

Not financial advice. Bet responsibly. 21+

{tags} #NBAslate #fullslate #NBAtonight""".strip()


def f5_caption(plays: list[dict], card_date: date | None = None) -> str:
    """Caption for F5 (First 5 Innings) totals card."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    mkt_short = {"batter_hits": "Hits", "batter_home_runs": "HRs",
                 "batter_rbis": "RBIs", "batter_total_bases": "TB"}
    lines = [
        f"⚾ F5 TOTALS — {date_str}",
        "First 5 innings only. No bullpen variance. Cleaner edge.",
        "━━━━━━━━━━━━━━━",
    ]
    for p in plays[:5]:
        matchup   = p.get("matchup", "")
        direction = p.get("direction", "OVER")
        line      = p.get("line", "")
        odds      = p.get("odds", 0)
        book      = p.get("book") or p.get("sportsbook", "")
        edge      = float(p.get("edge_pct", 0) or 0)
        odds_str  = f"{int(odds):+d}" if odds else ""
        lines.append(f"• {matchup} F5 {direction} {line}  {odds_str} @ {book}  |  +{edge:.1f}%")
    lines += [
        "━━━━━━━━━━━━━━━",
        "Model uses SP ERA × opponent K-rate for first 5 only — cleaner than full-game totals.",
        "Not financial advice. 21+",
        "#MLB #sportsbetting #F5 #firstfiveinnings #MLBpicks #sharpbetting #totals #baseballbetting",
    ]
    return "\n".join(lines)


def batter_props_caption(props: list[dict], card_date: date | None = None) -> str:
    """Caption for batter props card (hits/HRs/RBIs/TB)."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    mkt_short = {"batter_hits": "Hits", "batter_home_runs": "HRs",
                 "batter_rbis": "RBIs", "batter_total_bases": "TB"}
    lines = [
        f"⚾ BATTER PROPS — {date_str}",
        "Books price batters on season BA. We adjust for pitcher matchup. Gap = edge.",
        "━━━━━━━━━━━━━━━",
    ]
    for p in props[:6]:
        player    = p.get("player", "")
        market    = p.get("market", "")
        direction = p.get("direction", "OVER")
        line      = p.get("line", "")
        odds      = p.get("odds", 0)
        book      = p.get("book") or p.get("sportsbook", "")
        edge      = float(p.get("edge_pct", 0) or 0)
        odds_str  = f"{int(odds):+d}" if odds else ""
        ms        = mkt_short.get(market, market)
        lines.append(f"• {player} {direction} {line} {ms}  {odds_str} @ {book}  |  +{edge:.1f}%")
    lines += [
        "━━━━━━━━━━━━━━━",
        "Not financial advice. 21+",
        "#MLB #sportsbetting #batterprops #hitsbet #homerunbet #MLBprops #sharpbetting #propbets",
    ]
    return "\n".join(lines)


def print_nba_captions(
    picks: list[dict],
    props: list[dict],
    card_date: date | None = None,
    record: str | None = None,
    context_label: str = "NBA",
) -> None:
    """Print NBA game picks + props captions ready to copy-paste."""
    d = card_date or date.today()
    date_str = d.strftime("%b %-d")
    W = 68

    print(f"\n{'='*W}")
    print(f"  {context_label} CAPTIONS — {d.strftime('%B %d, %Y').upper()}")
    print(f"{'='*W}")

    print(f"\n── GAME PICKS {'─'*(W-15)}")
    print()
    print(nba_picks_caption(picks, date_str=date_str, record=record, card_date=d, context_label=context_label))

    if props:
        print(f"\n── PLAYER PROPS {'─'*(W-17)}")
        print()
        print(nba_props_caption(props, date_str=date_str, card_date=d, context_label=context_label))

    print(f"\n{'='*W}\n")
